algoritmo "Simulador de Inventário"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Ricardo Silva
// Descrição   : Registro, com sobreposição, de peças para um estoque
// Autor(a)    : Sage Anderson Almeida
// Data atual  : 08/04/2026
var

teste: caractere

inicio

teste <- "Este é um teste."
escreval ("Variável Teste")
escreva ("O valor da variável TESTE é: " + teste)

fimalgoritmo